version: '3.5'

services:
  app:
    build: backend/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
    environment:
      MC_TOKEN: loldude22changeMe
    ports:
      - "8071:5000"

  dwd:
    build: backend/dwd
    restart: unless-stopped
    volumes:
      - dwd:/data
    depends_on:
      - app

  tileserver:
    build: tileserver-gl-meteocool
    restart: unless-stopped
    volumes:
      - dwd:/data
      - ${PWD}/config.json:/etc/config.json
    depends_on:
      - app

volumes:
  dwd:
