version: '3.5'

# XXX TODO:
# - set time to localtime/host time inside the containers.

services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - meteo_mongo_db:/data/db

  web:
    build: frontend/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    ports:
      - "8040:8040"
      - "8041:8041"
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - ${PWD}/frontend/caddy/dev/Caddyfile:/etc/Caddyfile
      - pushpreview:/pushpreview
      - sslstore:/root/.caddy
        #    logging:
        #      driver: syslog
        #      options:
        #        syslog-address: "udp://logs7.papertrailapp.com:44195"
        #        tag: "{{.Name}}/{{.ID}}"

  app:
    build: backend/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
    environment:
      - TZ="Europe/Berlin"
      - DB_CONN="mongodb://mongo:27017/"
    depends_on:
      - mongo

  dwd:
    build: backend/dwd
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
      - DB_CONN="mongodb://mongo:27017/"
    env_file:
      - /etc/meteocool_env
    volumes:
      - dwd:/data
      - pushpreview:/pushpreview
      - /etc/meteocool/apns.json:/etc/apns.json
      - /etc/meteocool/authkey.p8:/etc/authkey.p8
    tmpfs:
      - /scratch
      - /forecast
    depends_on:
      - app
      - mongo

  tileserver:
    build: tileserver-gl-meteocool
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - dwd:/data
      - ${PWD}/tileserver-gl-meteocool/config:/etc/ts
    depends_on:
      - dwd

volumes:
  dwd:
  meteo_mongo_db:
  sslstore:
  pushpreview:
