version: '3.5'

# XXX TODO:
# - set time to localtime/host time inside the containers.

services:
  web:
    build: frontend/
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    ports:
            - "8040:8040"
            - "8041:8041"
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - ${PWD}/frontend/caddy/dev/Caddyfile:/etc/Caddyfile
      - sslstore:/root/.caddy
        #    logging:
        #      driver: syslog
        #      options:
        #        syslog-address: "udp://logs7.papertrailapp.com:44195"
        #        tag: "{{.Name}}/{{.ID}}"

  app:
    build: backend/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
    environment:
      - TZ="Europe/Berlin"

  dwd:
    build: backend/dwd
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - dwd:/data
    depends_on:
      - app

  tileserver:
    build: tileserver-gl-meteocool
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - dwd:/data
      - ${PWD}/tileserver-gl-meteocool/config-dev:/etc/ts
    depends_on:
      - dwd

        #elk:
        #  image: diecktator/elk:latest
        #  ports:
        #    - 11111:5601
        #    - 11112:5044
        #    - 11113:9200

volumes:
  dwd:
  sslstore:
