version: '3.5'

# XXX TODO:
# merge with the main docker-compose config somehow...

services:
  web:
    build: frontend/
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    ports:
      - "8040:8040"
      - "8041:8041"
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - ${PWD}/frontend/caddy/dev/Caddyfile:/etc/Caddyfile

  app:
    build: backend/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
    environment:
      - TZ="Europe/Berlin"

  dwd:
    build: backend/dwd
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - dwd:/data
    depends_on:
      - app

  tileserver:
    build: tileserver-gl-meteocool
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - dwd:/data
      - ${PWD}/tileserver-gl-meteocool/config-dev:/etc/ts
    depends_on:
      - dwd

volumes:
  dwd:
