version: '3.5'

services:
  app:
    environment:
      - RECORDING="true"
    volumes:
      - recording:/recording

  datasource:
    environment:
      - RECORDING="true"
    volumes:
      - recording:/recording

  dwd:
    environment:
      - RECORDING="true"
    volumes:
      - recording:/recording

volumes:
  recording:
