version: '3.5'

services:

  dwd:
    environment:
      - TZ="Europe/Berlin"
      - DB_CONN="mongodb://mongo:27017/"
    env_file:
      - /etc/meteocool_env
    volumes:
      - dwd:/data
      - pushpreview:/pushpreview
      - /etc/meteocool/apns.json:/etc/apns.json
      - /etc/meteocool/authkey.p8:/etc/authkey.p8
